### ISSUE TITLE
More API endpoints

### ISSUE THREAD

**Issue by JustinKnueppel** [seanmesserly/scorekeeper#14]
Proposed:

## Modify User
- `PUT /api/users/[userId]`
## Delete User
- `DELETE /api/users/[userId]`
## Get specific score information - would require adding `scoreId` to score responses
- `GET /api/users/[userId]/scores/[scoreId]`
## Modify score information
- `PUT /api/users/[userId]/scores/[scoreId]`
## Delete score information
- `DELETE /api/users/[userId]/scores/[scoreId]`
## Modify course
- `PUT /api/courses/[courseId]`
## Delete course
- `DELETE /api/courses/[courseId]`
## Get specific layout information - would require adding `layoutId` to layout responses
- `GET /api/courses/[courseId]/layouts/[layoutId]`
## Modify layout
- `PUT /api/courses/[courseId]/layouts/[layoutId]`
## Delete layout
- `DELETE /api/courses/[courseId]/layouts/[layoutId]`

**Comment by seanmesserly** [comment]
- By specific score information, you mean for a given scorecard correct (not the score on just one hole)?
- Definitely think using `layoutId` instead of `layoutName` is way better

**Comment by JustinKnueppel** [comment]
Correct the score endpoint is entirely to do with score cards. We can change the name if you think it makes sense but I think score might be descriptive enough. Also I agree with the layout name to ID change as well
